name: CI/CD Pipeline

on:
  push:
    branches: [ main, recurso-ci-cd ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar dependências
      run: |
        pip install fastapi uvicorn

    - name: Testar aplicação
      run: |
        python -c "from main import app; print('CI funcionando')"

  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
    - name: Simulando deploy
      run: |
        echo "Deploy iniciado..."
        echo "Aplicação enviada com sucesso!"
        echo "CD funcionando"

  docker:
    runs-on: ubuntu-latest
    needs: ci

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Build da imagem Docker
      run: |
        docker build -t projeto-devops .

    - name: Rodar container (teste)
      run: |
        docker run -d -p 8000:8000 projeto-devops